// AUTO-GENERATED - File generated by `figma2theme`, manual edits may be overwritten
// Generated from Figma file https://www.figma.com/file/4LsW1r8CbSiM1xTwfu22mb

import defaultTheme from '@chakra-ui/theme';

/**
 * Foundations
 */

const breakpoints = ['30rem', '40rem', '62rem', '80rem'];
export type Breakpoints = typeof breakpoints;

const colors = {
  portable: {
    almostBlack: '#181818',
    warmWhite: '#FCFCFC',
    robbie: '#6D2041',
    rose: '#E35740',
    fixation: '#257846',
    slow: '#FB7D10',
    mill: '#191F37',
    mash: '#133230',
    everyday: '#FFD337',
    cibi: '#4538DD',
    suzie: '#D9FF88',
    gem: '#5B2382',
    paradise: '#F9AAD0',
    classica: '#FBEFEC',
  },
  brand: {
    turquoise: '#40E0D0',
    coffee: {
      '50': '#FFE2C6',
      '100': '#EEC5AA',
      '200': '#D4AB91',
      '300': '#B99379',
      '400': '#A07B62',
      '500': '#87644C',
      '600': '#6F4E37',
      '700': '#573822',
      '800': '#40240F',
      '900': '#2C1000',
    },
  },
};
export type Colors = typeof colors;

const radii = {
  none: '0',
  sm: '0.125rem',
  md: '0.25rem',
  lg: '0.5rem',
  full: '9999px',
};
export type Radii = typeof radii;

const shadows = {
  sm: '0 1px 3px 0 rgba(0, 0, 0, 0.1), 0 1px 2px 0 rgba(0, 0, 0, 0.06)',
  md: '0 4px 6px 0 rgba(0, 0, 0, 0.1), 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
  'dark-lg':
    '0 0 0 0 rgba(0, 0, 0, 0.1), 0 5px 10px 0 rgba(0, 0, 0, 0.2), 0 15px 40px 0 rgba(0, 0, 0, 0.4)',
  lg: '0 10px 15px 0 rgba(0, 0, 0, 0.1), 0 4px 6px 0 rgba(0, 0, 0, 0.05)',
  xl: '0 20px 25px 0 rgba(0, 0, 0, 0.1), 0 10px 10px 0 rgba(0, 0, 0, 0.04)',
  '2xl': '0 25px 50px 0 rgba(0, 0, 0, 0.25)',
  outline: '0 0 0 0 rgba(66, 153, 225, 0.6)',
  inner: 'inset 0 2px 4px 0 rgba(0, 0, 0, 0.06)',
  none: 'none',
};
export type Shadows = typeof shadows;

const spaces = {
  '0': '0',
  '1': '0.25rem',
  '2': '0.5rem',
  '3': '0.75rem',
  '4': '1rem',
  '5': '1.25rem',
  '6': '1.5rem',
  '8': '2rem',
  '10': '2.5rem',
  '12': '3rem',
  '16': '4rem',
  '20': '5rem',
  '24': '6rem',
  '32': '8rem',
  '40': '10rem',
  '48': '12rem',
  '56': '14rem',
  '64': '16rem',
  px: '1px',
};
export type Spaces = typeof spaces;

const sizes = {
  ...spaces,
  ...{
    full: '100%',
    '3xs': '14rem',
    '2xs': '16rem',
    xs: '20rem',
    sm: '24rem',
    md: '28rem',
    lg: '32rem',
    xl: '36rem',
    '2xl': '42rem',
    '3xl': '48rem',
    '4xl': '56rem',
    '5xl': '64rem',
    '6xl': '72rem',
  },
  container: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
  },
};
export type Sizes = typeof sizes;

const typography = {
  letterSpacings: {
    tighter: '-0.05em',
    tight: '-0.025em',
    normal: '0',
    wide: '0.025em',
    wider: '0.05em',
    widest: '0.1em',
  },
  lineHeights: {
    normal: 'normal',
    none: '1',
    shorter: '1.25',
    short: '1.375',
    base: '1.5',
    tall: '1.625',
    taller: '2',
  },
  fontWeights: {
    hairline: 100,
    thin: 200,
    light: 300,
    normal: 400,
    medium: 500,
    semibold: 600,
    bold: 700,
    extrabold: 800,
    black: 900,
  },
  fonts: {
    heading: '"Montserrat", sans-serif',
    body: '"Open Sans", sans-serif',
    mono: '"Courier New", Courier, monospace',
  },
  fontSizes: {
    xs: '0.75rem',
    sm: '0.875rem',
    md: '1rem',
    lg: '1.125rem',
    xl: '1.25rem',
    '2xl': '1.5rem',
    '3xl': '1.875rem',
    '4xl': '2.25rem',
    '5xl': '3rem',
    '6xl': '4rem',
  },
};
export type Typography = typeof typography;

/**
 * Variants
 */

const textVariants = {
  body: {
    fontFamily: 'Open Sans',
    fontSize: ['1.125rem', '1.25rem', '1.375rem', '1.5rem', '1.625rem'],
    fontStyle: 'normal',
    fontWeight: '400',
    letterSpacing: '0em',
    lineHeight: 'normal',
  },
  caption: {
    fontFamily: 'Open Sans',
    fontSize: '1.125rem',
    fontStyle: 'italic',
    fontWeight: '400',
    letterSpacing: '0em',
    lineHeight: 'normal',
  },
};
export type TextVariants = typeof textVariants;

const headingVariants = {
  h1: {
    fontFamily: 'Montserrat',
    fontSize: ['1.5rem', '2.25rem', '3rem', '4rem', '4.5rem'],
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: '0em',
    lineHeight: 'normal',
  },
  h2: {
    fontFamily: 'Montserrat',
    fontSize: ['1.125rem', '1.5rem', '2.25rem', '3rem', '4rem'],
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: '0em',
    lineHeight: 'normal',
  },
  h3: {
    fontFamily: 'Montserrat',
    fontSize: ['0.875rem', '1.125rem', '1.5rem', '2.25rem', '3rem'],
    fontStyle: 'normal',
    fontWeight: '700',
    letterSpacing: '0em',
    lineHeight: 'normal',
  },
};
export type HeadingVariants = typeof headingVariants;

/**
 * Theme
 */

const theme = {
  ...defaultTheme,
  components: {
    ...defaultTheme.components,
    Heading: {
      ...defaultTheme.components.Heading,
      variants: headingVariants,
    },
    Text: {
      variants: textVariants,
    },
  },
  breakpoints: breakpoints,
  colors: {
    ...defaultTheme.colors,
    ...colors,
  },
  radii: radii,
  // shadows: shadows,
  spaces: spaces,
  sizes: sizes,
  fonts: typography.fonts,
  fontSizes: typography.fontSizes,
  fontWeights: typography.fontWeights,
  lineHeights: typography.lineHeights,
  letterSpacings: typography.letterSpacings,
};
export type Theme = typeof theme;

export default theme;
