version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/template/next-ts-chakra-ui"
    schedule:
      interval: "weekly"
  - package-ecosystem: "npm"
    directory: "/template/sveltekit"
    schedule:
      interval: "weekly"
